# Generated by Django 2.2.6 on 2019-11-04 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 11, 4, 19, 56, 32, 541012)),
        ),
    ]
