# Generated by Django 2.1.5 on 2019-10-14 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0002_userprofile_last_workout_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 14, 22, 21, 47, 244069)),
        ),
    ]
