# Generated by Django 2.2.6 on 2019-10-19 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0003_auto_20191014_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 19, 21, 47, 52, 686740)),
        ),
    ]
