# Generated by Django 2.2.6 on 2019-11-04 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0003_auto_20191104_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 11, 4, 21, 29, 14, 161861)),
        ),
    ]
