# Generated by Django 2.2.6 on 2019-10-25 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0004_auto_20191019_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to='exercise_demos/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 25, 22, 7, 43, 789197)),
        ),
    ]
