# Generated by Django 2.2.6 on 2019-10-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0004_auto_20191019_2147'),
        ('trainer_app', '0004_auto_20191019_2358'),
    ]

    operations = [
    ]
