# Generated by Django 2.2.6 on 2019-10-26 03:23

import datetime
from django.db import migrations, models
import trainer_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0005_auto_20191025_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to=trainer_app.models.exercise_image_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 26, 3, 23, 45, 581713)),
        ),
    ]
