# Generated by Django 2.2.6 on 2019-10-26 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0006_auto_20191026_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to='exercise_demos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 26, 4, 13, 37, 978526)),
        ),
    ]
