# Generated by Django 2.2.6 on 2019-10-27 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0006_auto_20191027_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_workout_completed',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 27, 1, 30, 29, 51828)),
        ),
    ]
