"""
Django settings for trainer_project project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .dev_settings import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['138.197.193.113', 'localhost']

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#be sure to set the envrionment variable: os.environ['DB_PASS'] = 'whatever the password is'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'trainer_project',
        'USER': 'zach',
        'PASSWORD': os.environ['DB_PASS'],
        'HOST': 'localhost',
        'PORT': '',
    }
}


STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR, ]
